config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root "rehbers#index" 
  resources :rehbers, :path=>"rehberler"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rehber.rb
class Rehber < ApplicationRecord
    has_attached_file :resim, styles: { medium: "300x300>", thumb: "100x100>" }, default_url:
"/images/:style/missing.png"
validates_attachment_content_type :resim, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rehbers_controller.rb
class RehbersController < ApplicationController
  before_action :set_rehber, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show] 

  # GET /rehbers
  # GET /rehbers.json
  def index
    @rehbers = Rehber.all
  end

  # GET /rehbers/1
  # GET /rehbers/1.json
  def show
  end

  # GET /rehbers/new
  def new
    @rehber = Rehber.new
  end

  # GET /rehbers/1/edit
  def edit
  end

  # POST /rehbers
  # POST /rehbers.json
  def create
    @rehber = Rehber.new(rehber_params)

    respond_to do |format|
      if @rehber.save
        format.html { redirect_to @rehber, notice: 'Rehber was successfully created.' }
        format.json { render :show, status: :created, location: @rehber }
      else
        format.html { render :new }
        format.json { render json: @rehber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rehbers/1
  # PATCH/PUT /rehbers/1.json
  def update
    respond_to do |format|
      if @rehber.update(rehber_params)
        format.html { redirect_to @rehber, notice: 'Rehber was successfully updated.' }
        format.json { render :show, status: :ok, location: @rehber }
      else
        format.html { render :edit }
        format.json { render json: @rehber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rehbers/1
  # DELETE /rehbers/1.json
  def destroy
    @rehber.destroy
    respond_to do |format|
      format.html { redirect_to rehbers_url, notice: 'Rehber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rehber
      @rehber = Rehber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rehber_params
      params.require(:rehber).permit(:isim, :sehir, :ozet, :resim)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rehbers_helper.rb
module RehbersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uygulama</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div id="wrapper" class="animate">
        <nav class="navbar header-top fixed-top navbar-expand-lg navbar-dark bg-dark">
          <span class="navbar-toggler-icon leftmenutrigger"></span>
          <a class="navbar-brand" href="#">GEZGİNLER</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav animate side-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">Anasayfa
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Side Menu Items</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-md-auto d-md-flex">
              <li class="nav-item">
                <a class="nav-link" href="#">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Top Menu Items</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
            </ul>
          </div>
        </nav>
        <%=render "shared/navbar"%>
          
    <%= yield %>
  </body>
</html>

app/views/rehbers/_form.html.erb
<%= form_with(model: rehber, local: true) do |form| %>
  <% if rehber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rehber.errors.count, "error") %> prohibited this rehber from being saved:</h2>

      <ul>
      <% rehber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isim %>
    <%= form.text_field :isim %>
  </div>

  <div class="field">
    <%= form.label :sehir %>
    <%= form.text_field :sehir %>
  </div>

  <div class="field">
    <%= form.label :ozet %>
    <%= form.text_area :ozet %>
  </div>
  
  <div 
  
  <div class="field">
 <%= form.label :resim %>
 <%= form.file_field :resim %>
</div>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rehbers/edit.html.erb
<h1>Editing Rehber</h1>

<%= render 'form', rehber: @rehber %>

<%= link_to 'Show', @rehber %> |
<%= link_to 'Back', rehbers_path %>

app/views/rehbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rehbers</h1>

<table>
  <thead>
    <tr>
      <th>Isim</th>
      <th>Sehir</th>
      <th>Ozet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rehbers.each do |rehber| %>
      <tr>
        <td><%= rehber.isim %></td>
        <td><%= rehber.sehir %></td>
        <td><%= rehber.ozet %></td>
        <td><%= image_tag rehber.resim.url(:thumb) if rehber.resim? %> </td>
        <td><%= link_to 'Show', rehber %></td>
        <td><%= link_to 'Edit', edit_rehber_path(rehber) %></td>
        <td><%= link_to 'Destroy', rehber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rehber', new_rehber_path %>

app/views/rehbers/new.html.erb
<h1>New Rehber</h1>

<%= render 'form', rehber: @rehber %>

<%= link_to 'Back', rehbers_path %>

app/views/rehbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isim:</strong>
  <%= @rehber.isim %>
</p>

<p>
  <strong>Sehir:</strong>
  <%= @rehber.sehir %>
</p>

<p>
  <strong>Ozet:</strong>
  <%= @rehber.ozet %>
</p>


<p>
    
    <%= image_tag @rehber.resim.url(:medium) if @rehber.resim? %>
</p>
<%= link_to 'Edit', edit_rehber_path(@rehber) %> |
<%= link_to 'Back', rehbers_path %>

app/views/shared/_navbar.html.erb




<div id="wrapper" class="animate">
 <nav class="navbar header-top fixed-top navbar-expand-lg navbar-dark bg-dark">
 <span class="navbar-toggler-icon leftmenutrigger"></span>
 <a class="navbar-brand" href="#">LOGO</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" datatarget="#navbarText" aria-controls="navbarText"
 aria-expanded="false" aria-label="Toggle navigation">
 <span class="navbar-toggler-icon"></span>
 </button>
 
 <p class="navbar-text pull-right"> <% if user_signed_in? %>
Logged in as <strong><%= current_user.email %></strong>.
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
<% else %>
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> | <%= link_to
"Login", new_user_session_path, :class => 'navbar-link' %>
<% end %> </p> 
 <div class="collapse navbar-collapse" id="navbarText">
 <ul class="navbar-nav animate side-nav">
 <li class="nav-item">
 <a class="nav-link" href="#">Home
 <span class="sr-only">(current)</span>
 </a>
 </li>
 <li class="nav-item">
 <a class="nav-link" href="#">Side Menu Items</a>
 </li>
 <li class="nav-item">
 <a class="nav-link" href="#">Pricing</a>
 </li>
 </ul>
 <ul class="navbar-nav ml-md-auto d-md-flex">
 <li class="nav-item">
 <a class="nav-link" href="#">Home
 <span class="sr-only">(current)</span>
 </a>
 </li>
 <li class="nav-item">
 <a class="nav-link" href="#">Top Menu Items</a>
 </li>
 <li class="nav-item">
 <a class="nav-link" href="#">Pricing</a>
 </li>
 </ul>
 </div>
 </nav>